env:
    token: "ENCRYPTED[f8530eb3583f20acd1f7c8ac8b68f23d024d2a7b33efc732b904c727f321bad19015dd6eacad3dd92d23268f53b3ba30]"
    chat_id: "ENCRYPTED[6be3b77ae0bf272cc8ba32b1243170b9eca1bfe586d5443822db3267a691ea80df336a78909136fe529df9cbb76b8050]"

task:
  name: "Scarlet-X-Kernel-Builder"
  timeout_in: 2h
  container:
      image: ubuntu:devel
      cpu: 8
      memory: 32G

  Build_script:
      - apt update && apt upgrade -y
      - ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && date
      - apt install -f -y git bison flex libxml2 curl locales libssl-dev bc device-tree-compiler libstdc++6 zip default-jre python3 python3-pip dpkg cpio bash python2 && pip3 install telegram-send
      - locale-gen en_US en_US.UTF-8
      - dpkg-reconfigure locales
      - bash builder.sh
