env:
    token: "ENCRYPTED[f8530eb3583f20acd1f7c8ac8b68f23d024d2a7b33efc732b904c727f321bad19015dd6eacad3dd92d23268f53b3ba30]"
    chat_id: "ENCRYPTED[cbfec673786c68fedf431179098bf8f7ec23c379de9776890803e22a95356c3db61eac9cef4473040546e3a12f62ce81]"

task:
  name: "Scarlet-X-Kernel-Builder"
  timeout_in: 2h
  container:
      image: atomxorg/arch-linux:kernel
      cpu: 8
      memory: 32G

  Build_script:
      - ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && date
      - locale-gen en_US en_US.UTF-8
      - bash builder.sh
