env:
    token: "ENCRYPTED[f8530eb3583f20acd1f7c8ac8b68f23d024d2a7b33efc732b904c727f321bad19015dd6eacad3dd92d23268f53b3ba30]"
    chat_id: "ENCRYPTED[6be3b77ae0bf272cc8ba32b1243170b9eca1bfe586d5443822db3267a691ea80df336a78909136fe529df9cbb76b8050]"

task:
  name: "Scarlet-X-Kernel-Builder"
  timeout_in: 2h
  container:
      image: atomxorg/arch-linux:latest
      cpu: 8
      memory: 32G

  Build_script:
      - ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && date
      - locale-gen en_US en_US.UTF-8
      - bash builder.sh
