env:
    token: "ENCRYPTED[!36c7a19303307957678730d64338086346831226a1abf804f755aa7ad8330398a49fa1964559a23e17ca138f10335860!]"
    chat_id: "ENCRYPTED[!6e7eccee25b11a8b31961f3c9af43cd95a2b7523af91e53992cddd33dc6175374d1e863aa9a44e0fe364bdcb9abc03e1!]"

task:
  name: "Scarlet-X-Kernel-Builder"
  timeout_in: 2h
  container:
      image: ghcr.io/neutron-toolchains/docker-image:arch-neutron
      cpu: 8
      memory: 32G

  Build_script:
      - ln -fs /usr/share/zoneinfo/Asia/Dhaka /etc/localtime && date
      - locale-gen en_US en_US.UTF-8
      - bash builder.sh
