env:
    TG_TOKEN: ""
    TG_CHAT_ID: ""
    TZ: "Asia/Kolkata"

task:
  name: "Kernel-Builder"
  timeout_in: 20m  
  container:
      image: navin136/builder:latest
      cpu: 8
      memory: 16G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - DEBIAN_FRONTEND=noninteractive
       - sudo apt install python2 -y
       - sudo ln -sf /usr/bin/python2 /usr/bin/python
       - mkdir -p /tmp/ccache
       - cd /tmp

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h

  Build_script:
      - bash build.sh
