env:
    BOT_API_KEY: "ENCRYPTED[f8530eb3583f20acd1f7c8ac8b68f23d024d2a7b33efc732b904c727f321bad19015dd6eacad3dd92d23268f53b3ba30]"
    CHAT_ID: "ENCRYPTED[6be3b77ae0bf272cc8ba32b1243170b9eca1bfe586d5443822db3267a691ea80df336a78909136fe529df9cbb76b8050]"
    TZ: "Asia/Kolkata"

task:
  name: "Scarlet-X-Kernel-Builder"
  timeout_in: 69m  
  container:
      image: navin136/builder:latest
      cpu: 8
      memory: 16G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - DEBIAN_FRONTEND=noninteractive
       - sudo apt install python2 -y
       - sudo ln -sf /usr/bin/python2 /usr/bin/python
       - mkdir -p /tmp
       - cd /tmp

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h

  Build_script:
      - bash build.sh
